# Generated by Django 3.1.5 on 2021-01-27 13:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210127_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 13, 40, 25, 559795, tzinfo=utc), verbose_name='Publicacion'),
        ),
    ]
