# Generated by Django 3.1.5 on 2021-01-27 14:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210127_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 14, 7, 20, 210060, tzinfo=utc), verbose_name='Publicacion'),
        ),
    ]
