# Generated by Django 3.1.5 on 2021-02-01 12:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210127_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 1, 12, 46, 54, 16067, tzinfo=utc), verbose_name='Publicacion'),
        ),
    ]
