# Generated by Django 3.1.5 on 2021-01-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='uptadated',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='link',
            name='key',
            field=models.SlugField(max_length=20, unique=True, verbose_name='Nombre clave'),
        ),
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Red social'),
        ),
    ]
